{% set name = "msavc" %}
{% set version = "0.1.20260925" %}
{% set git_tag = "v0.1.20260925.1" %}       # ← 新增变量

package:
  name: {{ name }}
  version: {{ version }}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/malabz/MSAvc/archive/refs/tags/v{{ git_tag }}.tar.gz
  sha256: 42f237d4200e83bd017bc5712dbe3625e6cf017bd43bb53debb16f8fe8056d14

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - boost-cpp
    - htslib
    - zlib
    - libdeflate
    - bzip2
    - xz
    - libcurl
  run:
    - boost-cpp
    - htslib
    - zlib
    - libdeflate
    - bzip2
    - xz
    - libcurl
    - bash

test:
  commands:
    - msavc --version
    - msavc_fasta --version
    - msavc_genome --version

about:
  home: https://github.com/malabz/MSAvc
  license: MIT
  summary: 'MSAvc: variation calling for genome-scale multiple sequence alignments'
